version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
        exclude-patterns:
          - "actions/*"
          - "github/*"
      github-owned-actions:
        patterns:
          - "actions/*"
          - "github/*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "maven"
    directory: "/"
    groups:
      maven:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: docker
    directory: /bmq-sdk/src/test/docker
    schedule:
      interval: daily

