name: 'Publish to Maven Central'

on: workflow_dispatch

permissions:
  contents: read

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    environment: release
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          java-package: jdk
          check-latest: true
          # Must match <publishingServerId> in the root pom's ossrh profile.
          server-id: central
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: GPG_KEY_PASSPHRASE

      - name: 'Publish to Maven Central'
        run: mvn --batch-mode -Possrh -Dmaven.test.skip=true -Dspotbugs.skip=true -Dgpg.keyname="$GPG_KEY_ID" deploy
        env:
          GPG_KEY_ID: ${{ secrets.GPG_KEY_ID }}
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
