name: 'Publish to Maven Central'

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
      - name: 'Publish snapshot to OSSRH'
        if: github.event_name == 'push'
        run: mvn -B -e -Possrh -DskipTests=true deploy
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
