name: 'Publish to Maven Central'

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  publish:
    name: 'Publish'
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          java-package: jdk
          check-latest: true
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_PASSWORD
          gpg-private-key: ${{ secrets.GPG_KEY }}
          gpg-passphrase: GPG_KEY_PASSPHRASE
      - name: 'Publish snapshot to OSSRH'
        run: mvn --batch-mode -Possrh -DskipTests=true release:prepare release:deploy
        env:
          GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
